version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"   # Change the port mapping from 5432 to 5433
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "example"
