import { User } from '../interfaces'

/** Dummy user data. */
export const sampleUserData: User[] = [
  { id: 101, name: 'Alice' },
  { id: 102, name: 'Bob' },
  { id: 103, name: 'Caroline' },
  { id: 104, name: 'Dave' },
]

export const sellBooks:any[]=[
  {
      _id: "61d8a1a07c5759ffd7087b4b",
      name: "Economic and Social Development",
      author: "J.K. Rowling",
      photo: "https://m.media-amazon.com/images/I/41iUAPGYyVL._AC_UF1000,1000_QL80_.jpg",
      condition: 5,
      category: "Economic Book",
      description: "Harry Potter just defines my childhood. This is in very good condition like new.",
      price: 190,
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: "No.12 Rail Gate, Noapara Road, Barasat",
      landmark: "near Shantimoy Abasan",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700124,
      __v: 0
  },
  {
      _id: "61d8a24c7c5759ffd7087bd6",
      name: "Organic Chemistry",
      author: "J.K. Rowling",
      photo: "https://dcassetcdn.com/design_img/2980308/133708/133708_16464623_2980308_f4627893_thumbnail.png",
      condition: 4,
      category: "Chemistry",
      description: "Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.",
      price: 240,
      seller_mail: "rajdipgupta019@gmail.com",
      seller_id: "61d89b24b5e39be80f3e2a34",
      address: "61, New Basudevpur Road, Belghoria",
      landmark: "Near Basudevpur Sangathni Club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700056,
      __v: 0,
      school: "",
      college: "Heritage Institute of Technology",
      study: "college"
  },
  {
      _id: "61d8a2d54f8f19dac916df91",
      name: "Assessing Knowledge",
      author: "Masashi Kishimoto",
      photo: "https://dcassetcdn.com/design_img/3371734/92203/92203_18549385_3371734_754da033_image.jpg",
      condition: 4,
      category: "IQ Book",
      description: "This manga is made for those who really love anime, and the book is in okay condition.",
      price: 120,
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: "Biswa Bangla Sarani, Sub-Central Business District (Action Area 1), Action Area I, Newtown",
      landmark: "opposite of Oikotan Club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700156,
      __v: 0
  },
  {
      _id: "61d8a507583f4f96afd09208",
      name: "Basic of English Language",
      author: "Morgan Housel",
      photo: "https://dcassetcdn.com/design_img/2104617/487821/487821_11152261_2104617_51a3ff92_image.png",
      condition: 4,
      category: "Self Growth",
      description: "Timeless lessons on wealth, greed, and happiness tremendously well written by the author. Such a life-changing book.",
      price: 155,
      seller_mail: "rajdeeptechbyparts019@gmail.com",
      seller_id: "61d89b3ba1e52b1e78a9d52d",
      address: "Sen Raleigh More, Panchgachia Road",
      landmark: "Near Asansol Engineering College",
      country: "India",
      state: "West Bengal",
      city: "Asansol",
      pin: 713341,
      __v: 0
  },
  {
      _id: "61d8a59b840d4ed8c02c9a96",
      name: "Probability and statistics for Computer Science",
      author: "Peter Thiel",
      photo: "https://cs.illinois.edu/_sitemanager/viewphoto.aspx?id=10325&s=300",
      condition: 5,
      category: "Computer Science",
      description: "The great secret of our time is that there are still uncharted frontiers to explore and new inventions to create. In Zero to One, legendary entrepreneur and investor Peter Thiel shows how we can find singular ways to create those new things. Thiel begins with the contrarian premise that we live in an age of technological stagnation, even if we’re too distracted by shiny mobile devices to notice. Information technology has improved rapidly, but there is no reason why progress should be limited to computers or Silicon Valley. Progress can be achieved in any industry or area of business. It comes from the most important skill that every leader must master: learning to think for yourself.",
      price: 130,
      seller_mail: "rajdeeptechbyparts019@gmail.com",
      seller_id: "61d89b3ba1e52b1e78a9d52d",
      address: "North Gate, Barrackpore Cantonment",
      landmark: "near Barrackpore Station",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700120,
      __v: 0
  },
  ]

export const donateBooks:any[]=[
  {
      _id: "61d89cffa9c084453bf22b6e",
      name: "Basic of Computer Science",
      author: "Chaya Prakashani",
      photo: "https://media.springernature.com/full/springer-static/cover-hires/book/978-1-4842-7107-0",
      condition: 5,
      description: "This is a very good book for WBSCE Student for Higher Secondary Examination. This is in almost perfect condition too.",
      seller_mail: "rajdipgupta019@gmail.com",
      seller_id: "61d89b24b5e39be80f3e2a34",
      address: "61, New Basudevpur Road, Belghoria",
      landmark: "Near Basudevpur Sangathani Club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700056,
      __v: 0
  },
  {
      _id: "61d89e57252fa78bb3ca1f6f",
      name: "Elementary Standard ML",
      author: "WBCHSE",
      photo: "https://m.media-amazon.com/images/I/51ixQRUWxCL._AC_UF1000,1000_QL80_.jpg",
      condition: 4,
      description: "This book is great for class 6 students who want to learn English",
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: " 205, Krishna Sadhukhan Rd, Naihati Urban, Naihati",
      landmark: "near udayan club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 743165,
      __v: 0
  },
  {
      _id: "61d89f911502b8cbd5665dfd",
      name: "Comprehensive Physics",
      author: "Kumar Narinder",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641586577/wdg0qwqxe3z4wpjt5k4f.jpg",
      condition: 4,
      description: "This book is great for fellow jee aspirants and those who are preparing boards also",
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: " Delhi-Kolkata Hwy (NH2), Siudihi More, Mouza Talberia, Asansol",
      landmark: "near 52 vadodora street",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 713359,
      __v: 0
  },
  {
      _id: "61d8a1c541ed22b063ee64ba",
      name: "DPG Class-XII",
      author: "Dutta Pal Guchait",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641587139/icwcd1r0k2l9ubfow0l5.jpg",
      condition: 3,
      description: "This is an a amazing book for Class XII WBSCE and CBSE Board Students to study physic. This is highly conceptual book and the theory is written in a lovely manner.",
      seller_mail: "rajdipgupta019@gmail.com",
      seller_id: "61d89b24b5e39be80f3e2a34",
      address: " 2RX9+WV4, Champaberia, Bangaon",
      landmark: "Near Bangaon Station",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 743235,
      __v: 0
  },
  {
      _id: "61d8a525840d4ed8c02c9a72",
      name: "Chemistry Part 1 Class 11",
      author: "NCERT",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641588004/rmwra1esjcunewb1y1zw.jpg",
      condition: 4,
      description: "This NCERT chemistry book is great in condition ans no page is torn",
      seller_mail: "sahadebajyoti7@gmail.com",
      seller_id: "61d89ac4b3800fa099c01172",
      address: "32, Rabindranagar.1st lane, P.O-Nimta",
      landmark: "opposite of samaj sebak sangha",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700049,
      __v: 0
  },  
]
export const storyBooks:any[]=[
  {
      _id: "61d8a1a07c5759ffd7087b4b",
      name: "Harry potter and sorcerer's stone",
      author: "J.K Rowling",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641587103/dn8lbdx7perabgazkccd.jpg",
      condition: 5,
      category: "Story Book",
      description: "Harry Potter just defines my childhood. This is in very good condition like new.",
      price: 190,
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: "No.12 Rail Gate, Noapara Road, Barasat",
      landmark: "near shantimoy abasan",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700124,
      __v: 0
  },
  {
      _id: "61d8a24c7c5759ffd7087bd6",
      name: "Harry Potter And The Philosophers Stone",
      author: "J .K. Rowling",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641587275/yujsksl9oakrefimpbxi.jpg",
      condition: 4,
      category: "Story Book",
      description: "Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.",
      price: 240,
      seller_mail: "rajdipgupta019@gmail.com",
      seller_id: "61d89b24b5e39be80f3e2a34",
      address: "61, New Basudevpur Road, Belghoria",
      landmark: "Near Basudevpur Sangathni Club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700056,
      __v: 0,
      school: "",
      college: "Heritage Institute of Technology",
      study: "college"
  },
  {
      _id: "61d8a2d54f8f19dac916df91",
      name: "Naruto vol 1",
      author: "mashashi kishimoto",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641587412/m20vj6lhrwhxb80ixiwe.jpg",
      condition: 4,
      category: "Story Book",
      description: "This manga is made for those who really loves anime and the book is in ok condition.",
      price: 120,
      seller_mail: "debajyotisaha14@gmail.com",
      seller_id: "61d89b23b5e39be80f3e2a30",
      address: "Biswa Bangla Sarani, Sub-Central Business District (Action Area 1), Action Area I, Newtown",
      landmark: "opposite of oikotan club",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 700156,
      __v: 0
  },
  {
      _id: "61d8a8e697f6e745a792e135",
      name: "Ruskin Bond Collection",
      author: "Ruskin Bond",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641588964/hnxobzjycn575uyx2mqp.jpg",
      condition: 5,
      category: "Story Book",
      description: "This book is great for those who love Indian classical stories. It is almost new. I have completed it a few days back.",
      price: 200,
      seller_mail: "sahadebajyoti7@gmail.com",
      seller_id: "61d89ac4b3800fa099c01172",
      address: "Overhead Water Tank, Kanpur - Lucknow Rd, Vijay Nagar Colony, Alambagh",
      landmark: "near amrabati restaurant",
      country: "India",
      state: "Uttar Pradesh",
      city: "Kanpur",
      pin: 226023,
      __v: 0
  },
  {
      _id: "61dd5f0fda3acb7a5f046504",
      name: "Inferno",
      author: "Dan Brown",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1641897742/u76tpbo1ue5djduq6dbv.jpg",
      condition: 5,
      category: "Story Book",
      description: "Book",
      price: 100,
      seller_mail: "anubhabhalder7@gmail.com",
      seller_id: "61dd3efd2c36b5e52861a964",
      address: "somewhere",
      landmark: "Darjeeling",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      pin: 1,
      __v: 0
  },
  {
      _id: "63f1892fa5f330db0224babd",
      name: "New Hampshire",
      author: "Sammy",
      photo: "http://res.cloudinary.com/bookleemedia/image/upload/v1676773678/g4imd0ex20xrzltpr9cy.jpg",
      condition: 3,
      category: "Story Book",
      description: "Cool Book",
      price: 3000,
      seller_mail: "sarvesh.cs2021@gmail.com",
      seller_id: "63f18838457fcfbd845c61c6",
      address: "Mumbai",
      landmark: "Opposite Station",
      country: "India",
      state: "Maharashtra",
      city: "Mumbai",
      pin: 411023,
      college: "Amrita School of Arts and Sciences - Mysore",
      school: "",
      study: "college",
      __v: 0
  }
]
export const countries:any[]= [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "North Macedonia",
    "DR Congo (Congo-Kinshasa)",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];